Question:
You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

    
Solution: BITWISE

Let's use BITWISE method to solve this problem
So, using XOR concept we will get our additional character, understand it visually :-
Here also let's say our character are:
s = abc
t = cabx
If we take XOR of every character. all the n character of s "abc" is similar to n character of t "cab". So, they will cancel each other. 
And we left with our answer.
s =   abc
t =   cbax
------------
ans -> x
-----------

    def findTheDifference(self, s: str, t: str) -> str:
        c = 0
        for cs in s: c ^= ord(cs) #ord is ASCII value
        for ct in t: c ^= ord(ct)
        return chr(c) #chr = convert ASCII into character
