Question:
You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

    
    
    
    
    
    
    
    
    
    
    
Solution: 
    
https://www.youtube.com/watch?v=sRwElQ_TOr8  

If both bits are the same, the XOR operator outputs 0. 
If both bits are different, the XOR operator outputs 1. 
    
    
    def findTheDifference(self, s: str, t: str) -> str:
        c = 0
        for cs in s: c ^= ord(cs) #ord is ASCII value
        for ct in t: c ^= ord(ct)
        return chr(c) #chr = convert ASCII into character
